site_name: avdev-sandbox
site_url: https://github.com/avstack-lab/avdev-sandbox
theme:
  name: material

plugins:
  - search  # To have search functionality on the document
  - mkdocstrings  # To generate documentation from the code docstrings

nav:
  - About:
    - Installation: about/installation.md
    - License: about/license.md
    - Release Notes: about/release-notes.md